FROM public.ecr.aws/lambda/python:3.8

RUN pip3 install pandas && \
	pip3 install numpy && \
	pip3 install boto3 && \
	pip3 install scipy && \
	pip3 install awswrangler

WORKDIR /

COPY processing.py ${LAMBDA_TASK_ROOT}

CMD [ "processing.handler" ]